apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  ports:
    - nodePort: 30001 
      port: 8888 
      protocol: TCP
      targetPort: 8888
  selector:
    app: http 
  type: NodePort
